name: SCAH Security Checks

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read

jobs:
  semgrep:
    uses: Scah-proj/scah-security/.github/workflows/semgrep.yml@d9c73034577ef0a3078818a6220cfbeb78202e5b

  developer-security-report:
    uses: Scah-proj/scah-security/.github/workflows/developer-security-report.yml@d9c73034577ef0a3078818a6220cfbeb78202e5b
    with:
      node-version: "20"
      working-directory: "."
    permissions:
      contents: read
      pull-requests: write
      issues: write
