name: SCAH Security Checks

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  semgrep:
    name: SCAH Semgrep Scan
    uses: SCAH-club/scah-security/.github/workflows/semgrep.yml@main
    permissions:
      contents: read

  developer-security-report:
    name: SCAH Security Gate
    uses: SCAH-club/scah-security/.github/workflows/developer-security-report.yml@main

    with:
      node-version: "22"
      working-directory: "."

    permissions:
      contents: read
      actions: read
      pull-requests: write
      issues: write
